import "./wireframe.css";
// Must follow wireframe.css: it overrides that ramp per industry (generated by
// scripts/gen-industry-tints.mjs; every rule is theme-qualified so import order
// never decides light vs dark).
import "./landing/industry-tint.css";
import styles from "./MarketingHome.module.css";
import { IndustryProvider } from "./landing/IndustryContext";
import { LandingNav } from "./landing/LandingNav";
import { Hero } from "./landing/Hero";
import { HowItWorks } from "./landing/HowItWorks";
import { WhySina } from "./landing/WhySina";
import { Pitch } from "./landing/Pitch";

/**
 * The Phase 9 landing, served at `/`. Copy is inline English for the wireframe
 * pass; the fidelity pass moves it to the catalogs.
 *
 * The `.sina-wireframe` marker scopes the black/gray/white token override
 * (wireframe.css).
 */
export function MarketingHome() {
  return (
    <div className="sina-wireframe">
      <IndustryProvider>
        <div className={styles.content}>
          <LandingNav />
          <main id="main">
            <Hero />
            <HowItWorks />
            <WhySina />
            <Pitch />
          </main>
        </div>
      </IndustryProvider>
    </div>
  );
}
